# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://xr.mikumikuar.com
title: MikuMikuXR
email: mikumikuar@126.com
author: x3bits
description: > # "Write an awesome description for your new site here. 
  MikuMikuXR官方站。
copyright: 'Copyright &copy; 2018 x3bits. 版权所有.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: APP下载
    url: https://pan.baidu.com/s/18K27EVxERtid2qW0z2S_PA
  - title: 源代码
    url: https://github.com/x3bits/MikuMikuXR
  - title: 作者博客
    url: http://mikumikuar.lofter.com